//! Host-side splat export and import utilities (PLY).

use std::fs::File;
use std::io::{BufRead, BufReader, BufWriter, Write};
use std::path::Path;

#[cfg(feature = "gpu")]
use crate::diff::diff_splat::sh_coeff_count_for_degree;
use thiserror::Error;

#[cfg(test)]
/// SH DC coefficient constant for RGB to SH conversion.
const SH_C0: f32 = 0.282_094_8;

/// Convert RGB [0,1] to SH DC coefficient.
#[cfg(test)]
fn rgb_to_sh_dc(rgb: f32) -> f32 {
    (rgb - 0.5) / SH_C0
}

#[derive(Debug, Clone)]
pub struct SplatMetadata {
    pub iterations: usize,
    pub final_loss: f32,
    pub gaussian_count: usize,
    /// SH degree used for the scene (0 = RGB only, 1-3 = SH coefficients).
    pub sh_degree: usize,
}

impl Default for SplatMetadata {
    fn default() -> Self {
        Self {
            iterations: 0,
            final_loss: 0.0,
            gaussian_count: 0,
            sh_degree: 0,
        }
    }
}

#[derive(Debug, Error)]
pub enum SceneIoError {
    #[error("failed to write scene {path}: {source}")]
    Write {
        path: String,
        source: std::io::Error,
    },
    #[error("failed to read scene {path}: {source}")]
    Read {
        path: String,
        source: std::io::Error,
    },
    #[error("invalid scene format: {message}")]
    InvalidFormat { message: String },
    #[error("parse error: {0}")]
    Parse(String),
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum PlyOpacityRepresentation {
    Probability,
    RawLogit,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum PlyShCoeffLayout {
    Interleaved,
    ChannelMajor,
}

fn write_ply_header<W: Write>(
    writer: &mut W,
    path: &Path,
    metadata: &SplatMetadata,
    vertex_count: usize,
) -> Result<(), SceneIoError> {
    writeln!(writer, "ply").map_err(|source| SceneIoError::Write {
        path: path.display().to_string(),
        source,
    })?;
    writeln!(writer, "format ascii 1.0").map_err(|source| SceneIoError::Write {
        path: path.display().to_string(),
        source,
    })?;
    writeln!(writer, "comment Generated by RustGS").map_err(|source| SceneIoError::Write {
        path: path.display().to_string(),
        source,
    })?;
    writeln!(writer, "comment iterations {}", metadata.iterations).map_err(|source| {
        SceneIoError::Write {
            path: path.display().to_string(),
            source,
        }
    })?;
    writeln!(writer, "comment final_loss {}", metadata.final_loss).map_err(|source| {
        SceneIoError::Write {
            path: path.display().to_string(),
            source,
        }
    })?;
    writeln!(writer, "comment sh_degree {}", metadata.sh_degree).map_err(|source| {
        SceneIoError::Write {
            path: path.display().to_string(),
            source,
        }
    })?;
    writeln!(writer, "comment opacity_representation raw_logit").map_err(|source| {
        SceneIoError::Write {
            path: path.display().to_string(),
            source,
        }
    })?;
    writeln!(writer, "comment sh_coeff_layout channel_major").map_err(|source| {
        SceneIoError::Write {
            path: path.display().to_string(),
            source,
        }
    })?;
    writeln!(writer, "element vertex {}", vertex_count).map_err(|source| SceneIoError::Write {
        path: path.display().to_string(),
        source,
    })?;
    for property in [
        "x", "y", "z", "nx", "ny", "nz", "f_dc_0", "f_dc_1", "f_dc_2",
    ] {
        writeln!(writer, "property float {property}").map_err(|source| SceneIoError::Write {
            path: path.display().to_string(),
            source,
        })?;
    }
    for i in 0..45 {
        writeln!(writer, "property float f_rest_{i}").map_err(|source| SceneIoError::Write {
            path: path.display().to_string(),
            source,
        })?;
    }
    for property in [
        "opacity", "scale_0", "scale_1", "scale_2", "rot_0", "rot_1", "rot_2", "rot_3",
    ] {
        writeln!(writer, "property float {property}").map_err(|source| SceneIoError::Write {
            path: path.display().to_string(),
            source,
        })?;
    }
    writeln!(writer, "end_header").map_err(|source| SceneIoError::Write {
        path: path.display().to_string(),
        source,
    })?;
    Ok(())
}

#[cfg(feature = "gpu")]
fn opacity_to_logit(opacity: f32) -> f32 {
    let clamped = opacity.clamp(1e-6, 1.0 - 1e-6);
    (clamped / (1.0 - clamped)).ln()
}

#[cfg(feature = "gpu")]
fn opacity_value_to_logit(value: f32, representation: PlyOpacityRepresentation) -> f32 {
    match representation {
        PlyOpacityRepresentation::Probability => opacity_to_logit(value),
        PlyOpacityRepresentation::RawLogit => value,
    }
}

#[cfg(feature = "gpu")]
fn interleaved_sh_rest_to_channel_major(values: &[f32]) -> Vec<f32> {
    let coeffs_per_channel = values.len() / 3;
    let mut reordered = Vec::with_capacity(values.len());
    for channel in 0..3 {
        for coeff_idx in 0..coeffs_per_channel {
            reordered.push(values[coeff_idx * 3 + channel]);
        }
    }
    reordered
}

#[cfg(feature = "gpu")]
fn channel_major_sh_rest_to_interleaved(values: &[f32]) -> Vec<f32> {
    let coeffs_per_channel = values.len() / 3;
    let mut reordered = Vec::with_capacity(values.len());
    for coeff_idx in 0..coeffs_per_channel {
        for channel in 0..3 {
            reordered.push(values[channel * coeffs_per_channel + coeff_idx]);
        }
    }
    reordered
}

#[cfg(feature = "gpu")]
pub fn save_splats_ply(
    path: &Path,
    splats: &crate::training::HostSplats,
    metadata: &SplatMetadata,
) -> Result<(), SceneIoError> {
    splats
        .validate()
        .map_err(|err| SceneIoError::InvalidFormat {
            message: err.to_string(),
        })?;

    let file = File::create(path).map_err(|source| SceneIoError::Write {
        path: path.display().to_string(),
        source,
    })?;
    let mut writer = BufWriter::new(file);
    write_ply_header(&mut writer, path, metadata, splats.len())?;

    let view = splats.as_view();
    let sh_coeff_row_width = sh_coeff_count_for_degree(view.sh_degree) * 3;

    for idx in 0..splats.len() {
        let position_base = idx * 3;
        let rotation_base = idx * 4;
        let sh_base = idx * sh_coeff_row_width;
        let sh_coeffs = &view.sh_coeffs[sh_base..sh_base + sh_coeff_row_width];

        write!(
            writer,
            "{} {} {} 0 0 0 {} {} {} ",
            view.positions[position_base],
            view.positions[position_base + 1],
            view.positions[position_base + 2],
            sh_coeffs[0],
            sh_coeffs[1],
            sh_coeffs[2],
        )
        .map_err(|source| SceneIoError::Write {
            path: path.display().to_string(),
            source,
        })?;

        let sh_rest = &sh_coeffs[3..];
        let sh_rest_channel_major = interleaved_sh_rest_to_channel_major(sh_rest);
        for i in 0..45 {
            let value = sh_rest_channel_major.get(i).copied().unwrap_or(0.0);
            write!(writer, "{} ", value).map_err(|source| SceneIoError::Write {
                path: path.display().to_string(),
                source,
            })?;
        }

        writeln!(
            writer,
            "{} {} {} {} {} {} {} {}",
            view.opacity_logits[idx],
            view.log_scales[position_base],
            view.log_scales[position_base + 1],
            view.log_scales[position_base + 2],
            view.rotations[rotation_base],
            view.rotations[rotation_base + 1],
            view.rotations[rotation_base + 2],
            view.rotations[rotation_base + 3],
        )
        .map_err(|source| SceneIoError::Write {
            path: path.display().to_string(),
            source,
        })?;
    }

    Ok(())
}

#[cfg(feature = "gpu")]
pub fn load_splats_ply(
    path: &Path,
) -> Result<(crate::training::HostSplats, SplatMetadata), SceneIoError> {
    let file = File::open(path).map_err(|source| SceneIoError::Read {
        path: path.display().to_string(),
        source,
    })?;
    let reader = BufReader::new(file);

    let mut metadata = SplatMetadata::default();
    let mut in_header = true;
    let mut expected_vertices: Option<usize> = None;
    let mut generated_by_rustgs = false;
    let mut opacity_representation: Option<PlyOpacityRepresentation> = None;
    let mut sh_coeff_layout: Option<PlyShCoeffLayout> = None;

    let mut positions = Vec::new();
    let mut log_scales = Vec::new();
    let mut rotations = Vec::new();
    let mut opacity_logits = Vec::new();
    let mut sh_coeffs = Vec::new();

    for line in reader.lines() {
        let line = line.map_err(|source| SceneIoError::Read {
            path: path.display().to_string(),
            source,
        })?;
        let trimmed = line.trim();

        if in_header {
            if trimmed == "comment Generated by RustGS" {
                generated_by_rustgs = true;
            } else if trimmed.starts_with("comment iterations ") {
                metadata.iterations = trimmed["comment iterations ".len()..]
                    .trim()
                    .parse()
                    .unwrap_or(0);
            } else if trimmed.starts_with("comment final_loss ") {
                metadata.final_loss = trimmed["comment final_loss ".len()..]
                    .trim()
                    .parse()
                    .unwrap_or(0.0);
            } else if trimmed.starts_with("comment sh_degree ") {
                metadata.sh_degree = trimmed["comment sh_degree ".len()..]
                    .trim()
                    .parse()
                    .unwrap_or(0);
            } else if trimmed.starts_with("comment SH degree: ") {
                metadata.sh_degree = trimmed["comment SH degree: ".len()..]
                    .trim()
                    .parse()
                    .unwrap_or(metadata.sh_degree);
            } else if trimmed.starts_with("comment opacity_representation ") {
                opacity_representation =
                    match trimmed["comment opacity_representation ".len()..].trim() {
                        "probability" => Some(PlyOpacityRepresentation::Probability),
                        "raw_logit" => Some(PlyOpacityRepresentation::RawLogit),
                        _ => None,
                    };
            } else if trimmed.starts_with("comment sh_coeff_layout ") {
                sh_coeff_layout = match trimmed["comment sh_coeff_layout ".len()..].trim() {
                    "interleaved" => Some(PlyShCoeffLayout::Interleaved),
                    "channel_major" => Some(PlyShCoeffLayout::ChannelMajor),
                    _ => None,
                };
            } else if trimmed.starts_with("element vertex ") {
                expected_vertices = trimmed["element vertex ".len()..]
                    .trim()
                    .parse::<usize>()
                    .ok();
            } else if trimmed == "end_header" {
                in_header = false;
            }
            continue;
        }

        if trimmed.is_empty() {
            continue;
        }

        let values: Vec<f32> = trimmed
            .split_whitespace()
            .map(|value| value.parse::<f32>())
            .collect::<Result<Vec<_>, _>>()
            .map_err(|err| SceneIoError::Parse(err.to_string()))?;

        if values.len() != 62 {
            return Err(SceneIoError::InvalidFormat {
                message: format!(
                    "expected 62 values per vertex in splat PLY, got {}",
                    values.len()
                ),
            });
        }

        if metadata.sh_degree > 3 {
            return Err(SceneIoError::InvalidFormat {
                message: format!(
                    "unsupported sh_degree {} in splat loader; current path supports up to degree 3",
                    metadata.sh_degree
                ),
            });
        }

        positions.extend_from_slice(&values[0..3]);
        log_scales.extend_from_slice(&values[55..58]);
        rotations.extend_from_slice(&values[58..62]);
        let representation = opacity_representation.unwrap_or_else(|| {
            if generated_by_rustgs {
                PlyOpacityRepresentation::Probability
            } else {
                PlyOpacityRepresentation::RawLogit
            }
        });
        opacity_logits.push(opacity_value_to_logit(values[54], representation));

        sh_coeffs.extend_from_slice(&values[6..9]);
        let sh_rest_to_keep = sh_coeff_count_for_degree(metadata.sh_degree)
            .saturating_sub(1)
            .saturating_mul(3);
        let sh_rest = &values[9..9 + sh_rest_to_keep.min(45)];
        let sh_layout = sh_coeff_layout.unwrap_or_else(|| {
            if generated_by_rustgs {
                PlyShCoeffLayout::Interleaved
            } else {
                PlyShCoeffLayout::ChannelMajor
            }
        });
        match sh_layout {
            PlyShCoeffLayout::Interleaved => sh_coeffs.extend_from_slice(sh_rest),
            PlyShCoeffLayout::ChannelMajor => {
                sh_coeffs.extend(channel_major_sh_rest_to_interleaved(sh_rest))
            }
        }
    }

    let parsed_vertices = opacity_logits.len();
    if let Some(expected) = expected_vertices {
        if parsed_vertices != expected {
            return Err(SceneIoError::InvalidFormat {
                message: format!(
                    "vertex count mismatch: header {}, parsed {}",
                    expected, parsed_vertices
                ),
            });
        }
    }

    if metadata.gaussian_count == 0 {
        metadata.gaussian_count = parsed_vertices;
    }

    let splats = crate::training::HostSplats::from_raw_parts(
        positions,
        log_scales,
        rotations,
        opacity_logits,
        sh_coeffs,
        metadata.sh_degree,
    )
    .map_err(|err| SceneIoError::InvalidFormat {
        message: err.to_string(),
    })?;

    Ok((splats, metadata))
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::tempdir;

    #[cfg(feature = "gpu")]
    #[test]
    fn test_save_splats_ply_roundtrip() {
        let dir = tempdir().unwrap();
        let path = dir.path().join("splats.ply");
        let metadata = SplatMetadata {
            iterations: 12,
            final_loss: 0.25,
            gaussian_count: 1,
            sh_degree: 0,
        };
        let splats = crate::training::HostSplats::from_raw_parts(
            vec![0.0, 0.0, 1.0],
            vec![0.1f32.ln(), 0.1f32.ln(), 0.1f32.ln()],
            vec![1.0, 0.0, 0.0, 0.0],
            vec![0.0],
            vec![rgb_to_sh_dc(0.2), rgb_to_sh_dc(0.3), rgb_to_sh_dc(0.4)],
            0,
        )
        .unwrap();

        save_splats_ply(&path, &splats, &metadata).unwrap();

        let (loaded, loaded_meta) = load_splats_ply(&path).unwrap();
        assert_eq!(loaded.len(), 1);
        assert_eq!(loaded_meta.iterations, 12);
        assert_eq!(loaded_meta.sh_degree, 0);
        assert!((loaded.opacity_logit(0) - splats.opacity_logit(0)).abs() < 1e-6);
    }

    #[cfg(feature = "gpu")]
    #[test]
    fn test_save_splats_ply_roundtrip_with_sh_coeffs() {
        let dir = tempdir().unwrap();
        let path = dir.path().join("splats_sh.ply");
        let metadata = SplatMetadata {
            iterations: 7,
            final_loss: 0.125,
            gaussian_count: 1,
            sh_degree: 3,
        };
        let mut sh_coeffs = vec![rgb_to_sh_dc(0.2), rgb_to_sh_dc(0.3), rgb_to_sh_dc(0.4)];
        sh_coeffs.extend((0..45).map(|idx| idx as f32 * 0.01));
        let splats = crate::training::HostSplats::from_raw_parts(
            vec![1.0, 2.0, 3.0],
            vec![0.2f32.ln(), 0.3f32.ln(), 0.4f32.ln()],
            vec![1.0, 0.0, 0.0, 0.0],
            vec![0.25],
            sh_coeffs.clone(),
            3,
        )
        .unwrap();

        save_splats_ply(&path, &splats, &metadata).unwrap();

        let (loaded, loaded_meta) = load_splats_ply(&path).unwrap();
        assert_eq!(loaded.len(), 1);
        assert_eq!(loaded_meta.sh_degree, 3);
        assert!((loaded.opacity_logit(0) - splats.opacity_logit(0)).abs() < 1e-6);
        for (actual, expected) in loaded.as_view().sh_coeffs.iter().zip(sh_coeffs.iter()) {
            assert!((actual - expected).abs() < 1e-6);
        }
    }

    #[cfg(feature = "gpu")]
    #[test]
    fn test_load_legacy_rustgs_probability_opacity() {
        let dir = tempdir().unwrap();
        let path = dir.path().join("legacy_probability.ply");
        let contents = concat!(
            "ply\n",
            "format ascii 1.0\n",
            "comment Generated by RustGS\n",
            "comment iterations 1\n",
            "comment final_loss 0.0\n",
            "comment sh_degree 0\n",
            "element vertex 1\n",
            "property float x\n",
            "property float y\n",
            "property float z\n",
            "property float nx\n",
            "property float ny\n",
            "property float nz\n",
            "property float f_dc_0\n",
            "property float f_dc_1\n",
            "property float f_dc_2\n",
            "property float f_rest_0\n",
            "property float f_rest_1\n",
            "property float f_rest_2\n",
            "property float f_rest_3\n",
            "property float f_rest_4\n",
            "property float f_rest_5\n",
            "property float f_rest_6\n",
            "property float f_rest_7\n",
            "property float f_rest_8\n",
            "property float f_rest_9\n",
            "property float f_rest_10\n",
            "property float f_rest_11\n",
            "property float f_rest_12\n",
            "property float f_rest_13\n",
            "property float f_rest_14\n",
            "property float f_rest_15\n",
            "property float f_rest_16\n",
            "property float f_rest_17\n",
            "property float f_rest_18\n",
            "property float f_rest_19\n",
            "property float f_rest_20\n",
            "property float f_rest_21\n",
            "property float f_rest_22\n",
            "property float f_rest_23\n",
            "property float f_rest_24\n",
            "property float f_rest_25\n",
            "property float f_rest_26\n",
            "property float f_rest_27\n",
            "property float f_rest_28\n",
            "property float f_rest_29\n",
            "property float f_rest_30\n",
            "property float f_rest_31\n",
            "property float f_rest_32\n",
            "property float f_rest_33\n",
            "property float f_rest_34\n",
            "property float f_rest_35\n",
            "property float f_rest_36\n",
            "property float f_rest_37\n",
            "property float f_rest_38\n",
            "property float f_rest_39\n",
            "property float f_rest_40\n",
            "property float f_rest_41\n",
            "property float f_rest_42\n",
            "property float f_rest_43\n",
            "property float f_rest_44\n",
            "property float opacity\n",
            "property float scale_0\n",
            "property float scale_1\n",
            "property float scale_2\n",
            "property float rot_0\n",
            "property float rot_1\n",
            "property float rot_2\n",
            "property float rot_3\n",
            "end_header\n",
            "0 0 1 0 0 0 0.1 0.2 0.3 ",
            "0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 ",
            "0.8 -2.3025851 -2.3025851 -2.3025851 1 0 0 0\n",
        );
        std::fs::write(&path, contents).unwrap();

        let (loaded, _) = load_splats_ply(&path).unwrap();
        assert!((loaded.opacity(0) - 0.8).abs() < 1e-6);
    }

    #[cfg(feature = "gpu")]
    #[test]
    fn test_load_external_raw_logit_opacity() {
        let dir = tempdir().unwrap();
        let path = dir.path().join("external_raw_logit.ply");
        let contents = concat!(
            "ply\n",
            "format ascii 1.0\n",
            "comment exported elsewhere\n",
            "comment iterations 1\n",
            "comment final_loss 0.0\n",
            "comment sh_degree 0\n",
            "element vertex 1\n",
            "property float x\n",
            "property float y\n",
            "property float z\n",
            "property float nx\n",
            "property float ny\n",
            "property float nz\n",
            "property float f_dc_0\n",
            "property float f_dc_1\n",
            "property float f_dc_2\n",
            "property float f_rest_0\n",
            "property float f_rest_1\n",
            "property float f_rest_2\n",
            "property float f_rest_3\n",
            "property float f_rest_4\n",
            "property float f_rest_5\n",
            "property float f_rest_6\n",
            "property float f_rest_7\n",
            "property float f_rest_8\n",
            "property float f_rest_9\n",
            "property float f_rest_10\n",
            "property float f_rest_11\n",
            "property float f_rest_12\n",
            "property float f_rest_13\n",
            "property float f_rest_14\n",
            "property float f_rest_15\n",
            "property float f_rest_16\n",
            "property float f_rest_17\n",
            "property float f_rest_18\n",
            "property float f_rest_19\n",
            "property float f_rest_20\n",
            "property float f_rest_21\n",
            "property float f_rest_22\n",
            "property float f_rest_23\n",
            "property float f_rest_24\n",
            "property float f_rest_25\n",
            "property float f_rest_26\n",
            "property float f_rest_27\n",
            "property float f_rest_28\n",
            "property float f_rest_29\n",
            "property float f_rest_30\n",
            "property float f_rest_31\n",
            "property float f_rest_32\n",
            "property float f_rest_33\n",
            "property float f_rest_34\n",
            "property float f_rest_35\n",
            "property float f_rest_36\n",
            "property float f_rest_37\n",
            "property float f_rest_38\n",
            "property float f_rest_39\n",
            "property float f_rest_40\n",
            "property float f_rest_41\n",
            "property float f_rest_42\n",
            "property float f_rest_43\n",
            "property float f_rest_44\n",
            "property float opacity\n",
            "property float scale_0\n",
            "property float scale_1\n",
            "property float scale_2\n",
            "property float rot_0\n",
            "property float rot_1\n",
            "property float rot_2\n",
            "property float rot_3\n",
            "end_header\n",
            "0 0 1 0 0 0 0.1 0.2 0.3 ",
            "0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 ",
            "2.0 -2.3025851 -2.3025851 -2.3025851 1 0 0 0\n",
        );
        std::fs::write(&path, contents).unwrap();

        let (loaded, _) = load_splats_ply(&path).unwrap();
        assert!((loaded.opacity_logit(0) - 2.0).abs() < 1e-6);
    }

    #[cfg(feature = "gpu")]
    #[test]
    fn test_load_external_channel_major_sh_coeffs() {
        let dir = tempdir().unwrap();
        let path = dir.path().join("external_channel_major_sh.ply");
        let contents = concat!(
            "ply\n",
            "format ascii 1.0\n",
            "comment Exported from Brush\n",
            "comment SH degree: 1\n",
            "element vertex 1\n",
            "property float x\n",
            "property float y\n",
            "property float z\n",
            "property float nx\n",
            "property float ny\n",
            "property float nz\n",
            "property float f_dc_0\n",
            "property float f_dc_1\n",
            "property float f_dc_2\n",
            "property float f_rest_0\n",
            "property float f_rest_1\n",
            "property float f_rest_2\n",
            "property float f_rest_3\n",
            "property float f_rest_4\n",
            "property float f_rest_5\n",
            "property float f_rest_6\n",
            "property float f_rest_7\n",
            "property float f_rest_8\n",
            "property float f_rest_9\n",
            "property float f_rest_10\n",
            "property float f_rest_11\n",
            "property float f_rest_12\n",
            "property float f_rest_13\n",
            "property float f_rest_14\n",
            "property float f_rest_15\n",
            "property float f_rest_16\n",
            "property float f_rest_17\n",
            "property float f_rest_18\n",
            "property float f_rest_19\n",
            "property float f_rest_20\n",
            "property float f_rest_21\n",
            "property float f_rest_22\n",
            "property float f_rest_23\n",
            "property float f_rest_24\n",
            "property float f_rest_25\n",
            "property float f_rest_26\n",
            "property float f_rest_27\n",
            "property float f_rest_28\n",
            "property float f_rest_29\n",
            "property float f_rest_30\n",
            "property float f_rest_31\n",
            "property float f_rest_32\n",
            "property float f_rest_33\n",
            "property float f_rest_34\n",
            "property float f_rest_35\n",
            "property float f_rest_36\n",
            "property float f_rest_37\n",
            "property float f_rest_38\n",
            "property float f_rest_39\n",
            "property float f_rest_40\n",
            "property float f_rest_41\n",
            "property float f_rest_42\n",
            "property float f_rest_43\n",
            "property float f_rest_44\n",
            "property float opacity\n",
            "property float scale_0\n",
            "property float scale_1\n",
            "property float scale_2\n",
            "property float rot_0\n",
            "property float rot_1\n",
            "property float rot_2\n",
            "property float rot_3\n",
            "end_header\n",
            "0 0 1 0 0 0 0.1 0.2 0.3 ",
            "1 2 3 4 5 6 7 8 9 ",
            "0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 ",
            "2.0 -2.3025851 -2.3025851 -2.3025851 1 0 0 0\n",
        );
        std::fs::write(&path, contents).unwrap();

        let (loaded, meta) = load_splats_ply(&path).unwrap();
        assert_eq!(meta.sh_degree, 1);
        assert_eq!(
            loaded.as_view().sh_coeffs,
            &[0.1, 0.2, 0.3, 1.0, 4.0, 7.0, 2.0, 5.0, 8.0, 3.0, 6.0, 9.0]
        );
    }
}
