//! Host-side splat export and import utilities (PLY).

use std::fs::File;
use std::io::{BufWriter, Write};
use std::path::Path;

#[cfg(feature = "gpu")]
use crate::sh::sh_coeff_count_for_degree;
use thiserror::Error;

#[cfg(test)]
use crate::sh::rgb_to_sh0_value as rgb_to_sh_dc;

#[derive(Debug, Clone)]
pub struct SplatMetadata {
    pub iterations: usize,
    pub final_loss: f32,
    pub gaussian_count: usize,
    /// SH degree used for the scene (0 = RGB only, 1-3 = SH coefficients).
    pub sh_degree: usize,
}

impl Default for SplatMetadata {
    fn default() -> Self {
        Self {
            iterations: 0,
            final_loss: 0.0,
            gaussian_count: 0,
            sh_degree: 0,
        }
    }
}

#[derive(Debug, Error)]
pub enum SceneIoError {
    #[error("failed to write scene {path}: {source}")]
    Write {
        path: String,
        source: std::io::Error,
    },
    #[error("failed to read scene {path}: {source}")]
    Read {
        path: String,
        source: std::io::Error,
    },
    #[error("invalid scene format: {message}")]
    InvalidFormat { message: String },
    #[error("parse error: {0}")]
    Parse(String),
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum PlyOpacityRepresentation {
    Probability,
    RawLogit,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum PlyShCoeffLayout {
    Interleaved,
    ChannelMajor,
}

#[cfg(feature = "gpu")]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum PlyFormat {
    Ascii,
    BinaryLittleEndian,
}

#[cfg(feature = "gpu")]
#[derive(Debug)]
struct ParsedPlyHeader {
    format: PlyFormat,
    vertex_count: usize,
    vertex_properties: Vec<String>,
    opacity_representation: Option<PlyOpacityRepresentation>,
    sh_coeff_layout: Option<PlyShCoeffLayout>,
    metadata: SplatMetadata,
    has_explicit_sh_degree: bool,
}

#[cfg(feature = "gpu")]
#[derive(Debug)]
struct VertexFieldMap {
    positions: [usize; 3],
    log_scales: [usize; 3],
    rotations: [usize; 4],
    opacity: usize,
    sh_dc: [usize; 3],
    sh_rest: Vec<usize>,
}

fn write_ply_header<W: Write>(
    writer: &mut W,
    path: &Path,
    metadata: &SplatMetadata,
    vertex_count: usize,
) -> Result<(), SceneIoError> {
    writeln!(writer, "ply").map_err(|source| SceneIoError::Write {
        path: path.display().to_string(),
        source,
    })?;
    writeln!(writer, "format ascii 1.0").map_err(|source| SceneIoError::Write {
        path: path.display().to_string(),
        source,
    })?;
    writeln!(writer, "comment Generated by RustGS").map_err(|source| SceneIoError::Write {
        path: path.display().to_string(),
        source,
    })?;
    writeln!(writer, "comment iterations {}", metadata.iterations).map_err(|source| {
        SceneIoError::Write {
            path: path.display().to_string(),
            source,
        }
    })?;
    writeln!(writer, "comment final_loss {}", metadata.final_loss).map_err(|source| {
        SceneIoError::Write {
            path: path.display().to_string(),
            source,
        }
    })?;
    writeln!(writer, "comment sh_degree {}", metadata.sh_degree).map_err(|source| {
        SceneIoError::Write {
            path: path.display().to_string(),
            source,
        }
    })?;
    writeln!(writer, "comment opacity_representation raw_logit").map_err(|source| {
        SceneIoError::Write {
            path: path.display().to_string(),
            source,
        }
    })?;
    writeln!(writer, "comment sh_coeff_layout channel_major").map_err(|source| {
        SceneIoError::Write {
            path: path.display().to_string(),
            source,
        }
    })?;
    writeln!(writer, "element vertex {}", vertex_count).map_err(|source| SceneIoError::Write {
        path: path.display().to_string(),
        source,
    })?;
    for property in [
        "x", "y", "z", "nx", "ny", "nz", "f_dc_0", "f_dc_1", "f_dc_2",
    ] {
        writeln!(writer, "property float {property}").map_err(|source| SceneIoError::Write {
            path: path.display().to_string(),
            source,
        })?;
    }
    for i in 0..45 {
        writeln!(writer, "property float f_rest_{i}").map_err(|source| SceneIoError::Write {
            path: path.display().to_string(),
            source,
        })?;
    }
    for property in [
        "opacity", "scale_0", "scale_1", "scale_2", "rot_0", "rot_1", "rot_2", "rot_3",
    ] {
        writeln!(writer, "property float {property}").map_err(|source| SceneIoError::Write {
            path: path.display().to_string(),
            source,
        })?;
    }
    writeln!(writer, "end_header").map_err(|source| SceneIoError::Write {
        path: path.display().to_string(),
        source,
    })?;
    Ok(())
}

#[cfg(feature = "gpu")]
fn opacity_to_logit(opacity: f32) -> f32 {
    let clamped = opacity.clamp(1e-6, 1.0 - 1e-6);
    (clamped / (1.0 - clamped)).ln()
}

#[cfg(feature = "gpu")]
fn opacity_value_to_logit(value: f32, representation: PlyOpacityRepresentation) -> f32 {
    match representation {
        PlyOpacityRepresentation::Probability => opacity_to_logit(value),
        PlyOpacityRepresentation::RawLogit => value,
    }
}

#[cfg(feature = "gpu")]
fn interleaved_sh_rest_to_channel_major(values: &[f32]) -> Vec<f32> {
    let coeffs_per_channel = values.len() / 3;
    let mut reordered = Vec::with_capacity(values.len());
    for channel in 0..3 {
        for coeff_idx in 0..coeffs_per_channel {
            reordered.push(values[coeff_idx * 3 + channel]);
        }
    }
    reordered
}

#[cfg(feature = "gpu")]
fn channel_major_sh_rest_to_interleaved(values: &[f32]) -> Vec<f32> {
    let coeffs_per_channel = values.len() / 3;
    let mut reordered = Vec::with_capacity(values.len());
    for coeff_idx in 0..coeffs_per_channel {
        for channel in 0..3 {
            reordered.push(values[channel * coeffs_per_channel + coeff_idx]);
        }
    }
    reordered
}

#[cfg(feature = "gpu")]
fn parse_ply_header(bytes: &[u8], path: &Path) -> Result<(ParsedPlyHeader, usize), SceneIoError> {
    let mut offset = 0usize;
    let mut saw_magic = false;
    let mut current_element: Option<String> = None;
    let mut header = ParsedPlyHeader {
        format: PlyFormat::Ascii,
        vertex_count: 0,
        vertex_properties: Vec::new(),
        opacity_representation: None,
        sh_coeff_layout: None,
        metadata: SplatMetadata::default(),
        has_explicit_sh_degree: false,
    };

    while offset < bytes.len() {
        let line_end = bytes[offset..]
            .iter()
            .position(|&byte| byte == b'\n')
            .map(|relative| offset + relative + 1)
            .unwrap_or(bytes.len());
        let raw_line = &bytes[offset..line_end];
        offset = line_end;

        let trimmed = std::str::from_utf8(raw_line)
            .map_err(|err| SceneIoError::Parse(err.to_string()))?
            .trim();

        if !saw_magic {
            if trimmed != "ply" {
                return Err(SceneIoError::InvalidFormat {
                    message: "missing PLY magic header".to_string(),
                });
            }
            saw_magic = true;
            continue;
        }

        if trimmed.starts_with("format ") {
            header.format = match trimmed["format ".len()..].trim() {
                "ascii 1.0" => PlyFormat::Ascii,
                "binary_little_endian 1.0" => PlyFormat::BinaryLittleEndian,
                other => {
                    return Err(SceneIoError::InvalidFormat {
                        message: format!("unsupported PLY format {other}"),
                    });
                }
            };
            continue;
        }

        if trimmed.starts_with("comment iterations ") {
            header.metadata.iterations = trimmed["comment iterations ".len()..]
                .trim()
                .parse()
                .unwrap_or(0);
        } else if trimmed.starts_with("comment final_loss ") {
            header.metadata.final_loss = trimmed["comment final_loss ".len()..]
                .trim()
                .parse()
                .unwrap_or(0.0);
        } else if trimmed.starts_with("comment sh_degree ") {
            header.metadata.sh_degree = trimmed["comment sh_degree ".len()..]
                .trim()
                .parse()
                .unwrap_or(0);
            header.has_explicit_sh_degree = true;
        } else if trimmed.starts_with("comment SH degree: ") {
            header.metadata.sh_degree = trimmed["comment SH degree: ".len()..]
                .trim()
                .parse()
                .unwrap_or(header.metadata.sh_degree);
            header.has_explicit_sh_degree = true;
        } else if trimmed.starts_with("comment opacity_representation ") {
            header.opacity_representation =
                match trimmed["comment opacity_representation ".len()..].trim() {
                    "probability" => Some(PlyOpacityRepresentation::Probability),
                    "raw_logit" => Some(PlyOpacityRepresentation::RawLogit),
                    _ => None,
                };
        } else if trimmed.starts_with("comment sh_coeff_layout ") {
            header.sh_coeff_layout = match trimmed["comment sh_coeff_layout ".len()..].trim() {
                "interleaved" => Some(PlyShCoeffLayout::Interleaved),
                "channel_major" => Some(PlyShCoeffLayout::ChannelMajor),
                _ => None,
            };
        } else if trimmed.starts_with("element ") {
            let mut parts = trimmed.split_whitespace();
            let _ = parts.next();
            let name = parts.next().unwrap_or_default();
            let count = parts
                .next()
                .unwrap_or_default()
                .parse::<usize>()
                .unwrap_or(0);
            current_element = Some(name.to_string());
            if name == "vertex" {
                header.vertex_count = count;
            }
        } else if trimmed.starts_with("property ") && current_element.as_deref() == Some("vertex") {
            let parts: Vec<_> = trimmed.split_whitespace().collect();
            if parts.get(1) == Some(&"list") {
                return Err(SceneIoError::InvalidFormat {
                    message: "list vertex properties are not supported in splat PLY loader"
                        .to_string(),
                });
            }
            if parts.len() != 3 {
                return Err(SceneIoError::InvalidFormat {
                    message: format!("invalid property declaration: {trimmed}"),
                });
            }
            match parts[1] {
                "float" | "float32" => {}
                other => {
                    return Err(SceneIoError::InvalidFormat {
                        message: format!(
                            "unsupported vertex property type {other} in {}",
                            path.display()
                        ),
                    });
                }
            }
            header.vertex_properties.push(parts[2].to_string());
        } else if trimmed == "end_header" {
            return Ok((header, offset));
        }
    }

    Err(SceneIoError::InvalidFormat {
        message: "missing end_header in splat PLY".to_string(),
    })
}

#[cfg(feature = "gpu")]
fn find_property_index(properties: &[String], name: &str) -> Result<usize, SceneIoError> {
    properties
        .iter()
        .position(|property| property == name)
        .ok_or_else(|| SceneIoError::InvalidFormat {
            message: format!("missing required PLY property {name}"),
        })
}

#[cfg(feature = "gpu")]
fn build_vertex_field_map(properties: &[String]) -> Result<VertexFieldMap, SceneIoError> {
    let mut sh_rest = properties
        .iter()
        .enumerate()
        .filter_map(|(idx, property)| {
            property
                .strip_prefix("f_rest_")
                .and_then(|suffix| suffix.parse::<usize>().ok())
                .map(|order| (order, idx))
        })
        .collect::<Vec<_>>();
    sh_rest.sort_by_key(|(order, _)| *order);

    Ok(VertexFieldMap {
        positions: [
            find_property_index(properties, "x")?,
            find_property_index(properties, "y")?,
            find_property_index(properties, "z")?,
        ],
        log_scales: [
            find_property_index(properties, "scale_0")?,
            find_property_index(properties, "scale_1")?,
            find_property_index(properties, "scale_2")?,
        ],
        opacity: find_property_index(properties, "opacity")?,
        rotations: [
            find_property_index(properties, "rot_0")?,
            find_property_index(properties, "rot_1")?,
            find_property_index(properties, "rot_2")?,
            find_property_index(properties, "rot_3")?,
        ],
        sh_dc: [
            find_property_index(properties, "f_dc_0")?,
            find_property_index(properties, "f_dc_1")?,
            find_property_index(properties, "f_dc_2")?,
        ],
        sh_rest: sh_rest.into_iter().map(|(_, idx)| idx).collect(),
    })
}

#[cfg(feature = "gpu")]
fn infer_sh_degree(
    explicit_degree: Option<usize>,
    sh_rest_count: usize,
) -> Result<usize, SceneIoError> {
    if let Some(degree) = explicit_degree {
        return Ok(degree);
    }
    if sh_rest_count == 0 {
        return Ok(0);
    }
    if sh_rest_count % 3 != 0 {
        return Err(SceneIoError::InvalidFormat {
            message: format!(
                "invalid f_rest property count {sh_rest_count}; expected a multiple of 3"
            ),
        });
    }

    let coeffs_per_channel = sh_rest_count / 3 + 1;
    let mut degree = 0usize;
    while sh_coeff_count_for_degree(degree) < coeffs_per_channel {
        degree += 1;
    }
    if sh_coeff_count_for_degree(degree) != coeffs_per_channel {
        return Err(SceneIoError::InvalidFormat {
            message: format!("could not infer SH degree from {sh_rest_count} rest coefficients"),
        });
    }
    Ok(degree)
}

#[cfg(feature = "gpu")]
fn append_vertex_values(
    values: &[f32],
    field_map: &VertexFieldMap,
    sh_degree: usize,
    opacity_representation: PlyOpacityRepresentation,
    sh_layout: PlyShCoeffLayout,
    positions: &mut Vec<f32>,
    log_scales: &mut Vec<f32>,
    rotations: &mut Vec<f32>,
    opacity_logits: &mut Vec<f32>,
    sh_coeffs: &mut Vec<f32>,
) -> Result<(), SceneIoError> {
    positions.extend(field_map.positions.iter().map(|&idx| values[idx]));
    log_scales.extend(field_map.log_scales.iter().map(|&idx| values[idx]));
    rotations.extend(field_map.rotations.iter().map(|&idx| values[idx]));
    opacity_logits.push(opacity_value_to_logit(
        values[field_map.opacity],
        opacity_representation,
    ));
    sh_coeffs.extend(field_map.sh_dc.iter().map(|&idx| values[idx]));

    let sh_rest_to_keep = sh_coeff_count_for_degree(sh_degree)
        .saturating_sub(1)
        .saturating_mul(3);
    if sh_rest_to_keep > 0 {
        let mut sh_rest = vec![0.0f32; sh_rest_to_keep];
        for (dst, src_idx) in field_map.sh_rest.iter().take(sh_rest_to_keep).enumerate() {
            sh_rest[dst] = values[*src_idx];
        }
        match sh_layout {
            PlyShCoeffLayout::Interleaved => sh_coeffs.extend_from_slice(&sh_rest),
            PlyShCoeffLayout::ChannelMajor => {
                sh_coeffs.extend(channel_major_sh_rest_to_interleaved(&sh_rest))
            }
        }
    }

    Ok(())
}

#[cfg(feature = "gpu")]
pub fn save_splats_ply(
    path: &Path,
    splats: &crate::core::HostSplats,
    metadata: &SplatMetadata,
) -> Result<(), SceneIoError> {
    splats
        .validate()
        .map_err(|err| SceneIoError::InvalidFormat {
            message: err.to_string(),
        })?;

    let file = File::create(path).map_err(|source| SceneIoError::Write {
        path: path.display().to_string(),
        source,
    })?;
    let mut writer = BufWriter::new(file);
    write_ply_header(&mut writer, path, metadata, splats.len())?;

    let view = splats.as_view();
    let sh_coeff_row_width = sh_coeff_count_for_degree(view.sh_degree) * 3;

    for idx in 0..splats.len() {
        let position_base = idx * 3;
        let rotation_base = idx * 4;
        let sh_base = idx * sh_coeff_row_width;
        let sh_coeffs = &view.sh_coeffs[sh_base..sh_base + sh_coeff_row_width];

        write!(
            writer,
            "{} {} {} 0 0 0 {} {} {} ",
            view.positions[position_base],
            view.positions[position_base + 1],
            view.positions[position_base + 2],
            sh_coeffs[0],
            sh_coeffs[1],
            sh_coeffs[2],
        )
        .map_err(|source| SceneIoError::Write {
            path: path.display().to_string(),
            source,
        })?;

        let sh_rest = &sh_coeffs[3..];
        let sh_rest_channel_major = interleaved_sh_rest_to_channel_major(sh_rest);
        for i in 0..45 {
            let value = sh_rest_channel_major.get(i).copied().unwrap_or(0.0);
            write!(writer, "{} ", value).map_err(|source| SceneIoError::Write {
                path: path.display().to_string(),
                source,
            })?;
        }

        writeln!(
            writer,
            "{} {} {} {} {} {} {} {}",
            view.opacity_logits[idx],
            view.log_scales[position_base],
            view.log_scales[position_base + 1],
            view.log_scales[position_base + 2],
            view.rotations[rotation_base],
            view.rotations[rotation_base + 1],
            view.rotations[rotation_base + 2],
            view.rotations[rotation_base + 3],
        )
        .map_err(|source| SceneIoError::Write {
            path: path.display().to_string(),
            source,
        })?;
    }

    Ok(())
}

#[cfg(feature = "gpu")]
pub fn load_splats_ply(
    path: &Path,
) -> Result<(crate::core::HostSplats, SplatMetadata), SceneIoError> {
    let bytes = std::fs::read(path).map_err(|source| SceneIoError::Read {
        path: path.display().to_string(),
        source,
    })?;
    let (header, body_offset) = parse_ply_header(&bytes, path)?;
    let field_map = build_vertex_field_map(&header.vertex_properties)?;

    let mut metadata = header.metadata;
    metadata.sh_degree = infer_sh_degree(
        if header.has_explicit_sh_degree {
            Some(metadata.sh_degree)
        } else {
            None
        },
        field_map.sh_rest.len(),
    )?;

    if metadata.sh_degree > 3 {
        return Err(SceneIoError::InvalidFormat {
            message: format!(
                "unsupported sh_degree {} in splat loader; current path supports up to degree 3",
                metadata.sh_degree
            ),
        });
    }

    let opacity_representation = header
        .opacity_representation
        .unwrap_or(PlyOpacityRepresentation::RawLogit);
    let sh_layout = header
        .sh_coeff_layout
        .unwrap_or(PlyShCoeffLayout::ChannelMajor);

    let mut positions = Vec::new();
    let mut log_scales = Vec::new();
    let mut rotations = Vec::new();
    let mut opacity_logits = Vec::new();
    let mut sh_coeffs = Vec::new();

    match header.format {
        PlyFormat::Ascii => {
            let body = std::str::from_utf8(&bytes[body_offset..])
                .map_err(|err| SceneIoError::Parse(err.to_string()))?;
            for line in body.lines() {
                let trimmed = line.trim();
                if trimmed.is_empty() {
                    continue;
                }

                let values: Vec<f32> = trimmed
                    .split_whitespace()
                    .map(|value| value.parse::<f32>())
                    .collect::<Result<Vec<_>, _>>()
                    .map_err(|err| SceneIoError::Parse(err.to_string()))?;
                if values.len() != header.vertex_properties.len() {
                    return Err(SceneIoError::InvalidFormat {
                        message: format!(
                            "expected {} values per vertex in splat PLY, got {}",
                            header.vertex_properties.len(),
                            values.len()
                        ),
                    });
                }
                append_vertex_values(
                    &values,
                    &field_map,
                    metadata.sh_degree,
                    opacity_representation,
                    sh_layout,
                    &mut positions,
                    &mut log_scales,
                    &mut rotations,
                    &mut opacity_logits,
                    &mut sh_coeffs,
                )?;
            }
        }
        PlyFormat::BinaryLittleEndian => {
            let property_count = header.vertex_properties.len();
            let row_bytes = property_count
                .checked_mul(std::mem::size_of::<f32>())
                .ok_or_else(|| SceneIoError::InvalidFormat {
                    message: "vertex row byte width overflow while reading PLY".to_string(),
                })?;
            let expected_bytes = header.vertex_count.checked_mul(row_bytes).ok_or_else(|| {
                SceneIoError::InvalidFormat {
                    message: "vertex byte size overflow while reading PLY".to_string(),
                }
            })?;
            let body = &bytes[body_offset..];
            if body.len() < expected_bytes {
                return Err(SceneIoError::InvalidFormat {
                    message: format!(
                        "binary PLY truncated: expected at least {expected_bytes} bytes, got {}",
                        body.len()
                    ),
                });
            }

            let mut cursor = 0usize;
            let mut values = vec![0.0f32; property_count];
            for _ in 0..header.vertex_count {
                for value in &mut values {
                    let chunk: [u8; 4] = body[cursor..cursor + 4].try_into().map_err(|_| {
                        SceneIoError::InvalidFormat {
                            message: "failed to decode binary PLY float".to_string(),
                        }
                    })?;
                    *value = f32::from_le_bytes(chunk);
                    cursor += 4;
                }
                append_vertex_values(
                    &values,
                    &field_map,
                    metadata.sh_degree,
                    opacity_representation,
                    sh_layout,
                    &mut positions,
                    &mut log_scales,
                    &mut rotations,
                    &mut opacity_logits,
                    &mut sh_coeffs,
                )?;
            }
        }
    }

    let parsed_vertices = opacity_logits.len();
    if parsed_vertices != header.vertex_count {
        return Err(SceneIoError::InvalidFormat {
            message: format!(
                "vertex count mismatch: header {}, parsed {}",
                header.vertex_count, parsed_vertices
            ),
        });
    }

    if metadata.gaussian_count == 0 {
        metadata.gaussian_count = parsed_vertices;
    }

    let splats = crate::core::HostSplats::from_raw_parts(
        positions,
        log_scales,
        rotations,
        opacity_logits,
        sh_coeffs,
        metadata.sh_degree,
    )
    .map_err(|err| SceneIoError::InvalidFormat {
        message: err.to_string(),
    })?;

    Ok((splats, metadata))
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::tempdir;

    #[cfg(feature = "gpu")]
    #[test]
    fn test_save_splats_ply_roundtrip() {
        let dir = tempdir().unwrap();
        let path = dir.path().join("splats.ply");
        let metadata = SplatMetadata {
            iterations: 12,
            final_loss: 0.25,
            gaussian_count: 1,
            sh_degree: 0,
        };
        let splats = crate::core::HostSplats::from_raw_parts(
            vec![0.0, 0.0, 1.0],
            vec![0.1f32.ln(), 0.1f32.ln(), 0.1f32.ln()],
            vec![1.0, 0.0, 0.0, 0.0],
            vec![0.0],
            vec![rgb_to_sh_dc(0.2), rgb_to_sh_dc(0.3), rgb_to_sh_dc(0.4)],
            0,
        )
        .unwrap();

        save_splats_ply(&path, &splats, &metadata).unwrap();

        let (loaded, loaded_meta) = load_splats_ply(&path).unwrap();
        assert_eq!(loaded.len(), 1);
        assert_eq!(loaded_meta.iterations, 12);
        assert_eq!(loaded_meta.sh_degree, 0);
        assert!((loaded.opacity_logit(0) - splats.opacity_logit(0)).abs() < 1e-6);
    }

    #[cfg(feature = "gpu")]
    #[test]
    fn test_save_splats_ply_roundtrip_with_sh_coeffs() {
        let dir = tempdir().unwrap();
        let path = dir.path().join("splats_sh.ply");
        let metadata = SplatMetadata {
            iterations: 7,
            final_loss: 0.125,
            gaussian_count: 1,
            sh_degree: 3,
        };
        let mut sh_coeffs = vec![rgb_to_sh_dc(0.2), rgb_to_sh_dc(0.3), rgb_to_sh_dc(0.4)];
        sh_coeffs.extend((0..45).map(|idx| idx as f32 * 0.01));
        let splats = crate::core::HostSplats::from_raw_parts(
            vec![1.0, 2.0, 3.0],
            vec![0.2f32.ln(), 0.3f32.ln(), 0.4f32.ln()],
            vec![1.0, 0.0, 0.0, 0.0],
            vec![0.25],
            sh_coeffs.clone(),
            3,
        )
        .unwrap();

        save_splats_ply(&path, &splats, &metadata).unwrap();

        let (loaded, loaded_meta) = load_splats_ply(&path).unwrap();
        assert_eq!(loaded.len(), 1);
        assert_eq!(loaded_meta.sh_degree, 3);
        assert!((loaded.opacity_logit(0) - splats.opacity_logit(0)).abs() < 1e-6);
        for (actual, expected) in loaded.as_view().sh_coeffs.iter().zip(sh_coeffs.iter()) {
            assert!((actual - expected).abs() < 1e-6);
        }
    }

    #[cfg(feature = "gpu")]
    #[test]
    fn test_load_external_raw_logit_opacity() {
        let dir = tempdir().unwrap();
        let path = dir.path().join("external_raw_logit.ply");
        let contents = concat!(
            "ply\n",
            "format ascii 1.0\n",
            "comment exported elsewhere\n",
            "comment iterations 1\n",
            "comment final_loss 0.0\n",
            "comment sh_degree 0\n",
            "element vertex 1\n",
            "property float x\n",
            "property float y\n",
            "property float z\n",
            "property float nx\n",
            "property float ny\n",
            "property float nz\n",
            "property float f_dc_0\n",
            "property float f_dc_1\n",
            "property float f_dc_2\n",
            "property float f_rest_0\n",
            "property float f_rest_1\n",
            "property float f_rest_2\n",
            "property float f_rest_3\n",
            "property float f_rest_4\n",
            "property float f_rest_5\n",
            "property float f_rest_6\n",
            "property float f_rest_7\n",
            "property float f_rest_8\n",
            "property float f_rest_9\n",
            "property float f_rest_10\n",
            "property float f_rest_11\n",
            "property float f_rest_12\n",
            "property float f_rest_13\n",
            "property float f_rest_14\n",
            "property float f_rest_15\n",
            "property float f_rest_16\n",
            "property float f_rest_17\n",
            "property float f_rest_18\n",
            "property float f_rest_19\n",
            "property float f_rest_20\n",
            "property float f_rest_21\n",
            "property float f_rest_22\n",
            "property float f_rest_23\n",
            "property float f_rest_24\n",
            "property float f_rest_25\n",
            "property float f_rest_26\n",
            "property float f_rest_27\n",
            "property float f_rest_28\n",
            "property float f_rest_29\n",
            "property float f_rest_30\n",
            "property float f_rest_31\n",
            "property float f_rest_32\n",
            "property float f_rest_33\n",
            "property float f_rest_34\n",
            "property float f_rest_35\n",
            "property float f_rest_36\n",
            "property float f_rest_37\n",
            "property float f_rest_38\n",
            "property float f_rest_39\n",
            "property float f_rest_40\n",
            "property float f_rest_41\n",
            "property float f_rest_42\n",
            "property float f_rest_43\n",
            "property float f_rest_44\n",
            "property float opacity\n",
            "property float scale_0\n",
            "property float scale_1\n",
            "property float scale_2\n",
            "property float rot_0\n",
            "property float rot_1\n",
            "property float rot_2\n",
            "property float rot_3\n",
            "end_header\n",
            "0 0 1 0 0 0 0.1 0.2 0.3 ",
            "0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 ",
            "2.0 -2.3025851 -2.3025851 -2.3025851 1 0 0 0\n",
        );
        std::fs::write(&path, contents).unwrap();

        let (loaded, _) = load_splats_ply(&path).unwrap();
        assert!((loaded.opacity_logit(0) - 2.0).abs() < 1e-6);
    }

    #[cfg(feature = "gpu")]
    #[test]
    fn test_load_external_channel_major_sh_coeffs() {
        let dir = tempdir().unwrap();
        let path = dir.path().join("external_channel_major_sh.ply");
        let contents = concat!(
            "ply\n",
            "format ascii 1.0\n",
            "comment Exported from Brush\n",
            "comment SH degree: 1\n",
            "element vertex 1\n",
            "property float x\n",
            "property float y\n",
            "property float z\n",
            "property float nx\n",
            "property float ny\n",
            "property float nz\n",
            "property float f_dc_0\n",
            "property float f_dc_1\n",
            "property float f_dc_2\n",
            "property float f_rest_0\n",
            "property float f_rest_1\n",
            "property float f_rest_2\n",
            "property float f_rest_3\n",
            "property float f_rest_4\n",
            "property float f_rest_5\n",
            "property float f_rest_6\n",
            "property float f_rest_7\n",
            "property float f_rest_8\n",
            "property float f_rest_9\n",
            "property float f_rest_10\n",
            "property float f_rest_11\n",
            "property float f_rest_12\n",
            "property float f_rest_13\n",
            "property float f_rest_14\n",
            "property float f_rest_15\n",
            "property float f_rest_16\n",
            "property float f_rest_17\n",
            "property float f_rest_18\n",
            "property float f_rest_19\n",
            "property float f_rest_20\n",
            "property float f_rest_21\n",
            "property float f_rest_22\n",
            "property float f_rest_23\n",
            "property float f_rest_24\n",
            "property float f_rest_25\n",
            "property float f_rest_26\n",
            "property float f_rest_27\n",
            "property float f_rest_28\n",
            "property float f_rest_29\n",
            "property float f_rest_30\n",
            "property float f_rest_31\n",
            "property float f_rest_32\n",
            "property float f_rest_33\n",
            "property float f_rest_34\n",
            "property float f_rest_35\n",
            "property float f_rest_36\n",
            "property float f_rest_37\n",
            "property float f_rest_38\n",
            "property float f_rest_39\n",
            "property float f_rest_40\n",
            "property float f_rest_41\n",
            "property float f_rest_42\n",
            "property float f_rest_43\n",
            "property float f_rest_44\n",
            "property float opacity\n",
            "property float scale_0\n",
            "property float scale_1\n",
            "property float scale_2\n",
            "property float rot_0\n",
            "property float rot_1\n",
            "property float rot_2\n",
            "property float rot_3\n",
            "end_header\n",
            "0 0 1 0 0 0 0.1 0.2 0.3 ",
            "1 2 3 4 5 6 7 8 9 ",
            "0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 ",
            "2.0 -2.3025851 -2.3025851 -2.3025851 1 0 0 0\n",
        );
        std::fs::write(&path, contents).unwrap();

        let (loaded, meta) = load_splats_ply(&path).unwrap();
        assert_eq!(meta.sh_degree, 1);
        assert_eq!(
            loaded.as_view().sh_coeffs,
            &[0.1, 0.2, 0.3, 1.0, 4.0, 7.0, 2.0, 5.0, 8.0, 3.0, 6.0, 9.0]
        );
    }

    #[cfg(feature = "gpu")]
    #[test]
    fn test_load_binary_brush_export_ply() {
        let dir = tempdir().unwrap();
        let path = dir.path().join("brush_binary_export.ply");

        let mut bytes = Vec::new();
        bytes.extend_from_slice(
            concat!(
                "ply\n",
                "format binary_little_endian 1.0\n",
                "comment Exported from Brush\n",
                "comment SH degree: 3\n",
                "comment SplatRenderMode: default\n",
                "element vertex 1\n",
                "property float x\n",
                "property float y\n",
                "property float z\n",
                "property float scale_0\n",
                "property float scale_1\n",
                "property float scale_2\n",
                "property float opacity\n",
                "property float rot_0\n",
                "property float rot_1\n",
                "property float rot_2\n",
                "property float rot_3\n",
                "property float f_dc_0\n",
                "property float f_dc_1\n",
                "property float f_dc_2\n",
                "property float f_rest_0\n",
                "property float f_rest_1\n",
                "property float f_rest_2\n",
                "property float f_rest_3\n",
                "property float f_rest_4\n",
                "property float f_rest_5\n",
                "property float f_rest_6\n",
                "property float f_rest_7\n",
                "property float f_rest_8\n",
                "property float f_rest_9\n",
                "property float f_rest_10\n",
                "property float f_rest_11\n",
                "property float f_rest_12\n",
                "property float f_rest_13\n",
                "property float f_rest_14\n",
                "property float f_rest_15\n",
                "property float f_rest_16\n",
                "property float f_rest_17\n",
                "property float f_rest_18\n",
                "property float f_rest_19\n",
                "property float f_rest_20\n",
                "property float f_rest_21\n",
                "property float f_rest_22\n",
                "property float f_rest_23\n",
                "property float f_rest_24\n",
                "property float f_rest_25\n",
                "property float f_rest_26\n",
                "property float f_rest_27\n",
                "property float f_rest_28\n",
                "property float f_rest_29\n",
                "property float f_rest_30\n",
                "property float f_rest_31\n",
                "property float f_rest_32\n",
                "property float f_rest_33\n",
                "property float f_rest_34\n",
                "property float f_rest_35\n",
                "property float f_rest_36\n",
                "property float f_rest_37\n",
                "property float f_rest_38\n",
                "property float f_rest_39\n",
                "property float f_rest_40\n",
                "property float f_rest_41\n",
                "property float f_rest_42\n",
                "property float f_rest_43\n",
                "property float f_rest_44\n",
                "end_header\n",
            )
            .as_bytes(),
        );

        let mut row = vec![
            1.0f32, 2.0, 3.0, -2.3025851, -1.609438, -1.2039728, 2.0, 1.0, 0.0, 0.0, 0.0, 0.1, 0.2,
            0.3,
        ];
        row.extend((1..=45).map(|value| value as f32));
        for value in row {
            bytes.extend_from_slice(&value.to_le_bytes());
        }
        std::fs::write(&path, bytes).unwrap();

        let (loaded, meta) = load_splats_ply(&path).unwrap();
        assert_eq!(meta.sh_degree, 3);
        assert_eq!(loaded.position(0), [1.0, 2.0, 3.0]);
        assert!((loaded.opacity_logit(0) - 2.0).abs() < 1e-6);

        let mut expected = vec![0.1, 0.2, 0.3];
        for coeff_idx in 0..15 {
            expected.push((coeff_idx + 1) as f32);
            expected.push((coeff_idx + 16) as f32);
            expected.push((coeff_idx + 31) as f32);
        }
        assert_eq!(loaded.as_view().sh_coeffs, expected.as_slice());
    }
}
