//! STL File Format Support
//!
//! STereoLithography format for 3D printing applications.

use crate::RustMesh;
use std::collections::HashMap;
use std::fs::File;
use std::io::{self, BufRead, BufReader, BufWriter, Read, Write};
use std::path::Path;

/// STL file format variant
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum StlFormat {
    /// ASCII text format
    Ascii,
    /// Binary format
    Binary,
}

// ============================================================================
// STL Writing Implementation
// ============================================================================

/// Write mesh to STL file
pub fn write_stl(mesh: &RustMesh, path: impl AsRef<Path>, format: StlFormat) -> io::Result<()> {
    match format {
        StlFormat::Ascii => write_stl_ascii(mesh, path),
        StlFormat::Binary => write_stl_binary(mesh, path),
    }
}

/// Write mesh to ASCII STL file
fn write_stl_ascii(mesh: &RustMesh, path: impl AsRef<Path>) -> io::Result<()> {
    let file = File::create(path)?;
    let mut writer = BufWriter::new(file);

    writeln!(writer, "solid mesh")?;

    for fh in mesh.faces() {
        // Get face vertices
        let verts: Vec<_> = mesh.face_vertices_vec(fh);
        if verts.len() < 3 {
            continue;
        }

        // Compute face normal
        let p0 = mesh.point(verts[0]).unwrap_or(glam::Vec3::ZERO);
        let p1 = mesh.point(verts[1]).unwrap_or(glam::Vec3::ZERO);
        let p2 = mesh.point(verts[2]).unwrap_or(glam::Vec3::ZERO);

        let edge1 = p1 - p0;
        let edge2 = p2 - p0;
        let normal = edge1.cross(edge2).normalize_or_zero();

        writeln!(
            writer,
            "facet normal {} {} {}",
            normal.x, normal.y, normal.z
        )?;
        writeln!(writer, "  outer loop")?;

        for vh in &verts {
            let p = mesh.point(*vh).unwrap_or(glam::Vec3::ZERO);
            writeln!(writer, "    vertex {} {} {}", p.x, p.y, p.z)?;
        }

        writeln!(writer, "  endloop")?;
        writeln!(writer, "endfacet")?;
    }

    writeln!(writer, "endsolid mesh")?;

    writer.flush()?;
    Ok(())
}

/// Write mesh to binary STL file
fn write_stl_binary(mesh: &RustMesh, path: impl AsRef<Path>) -> io::Result<()> {
    let file = File::create(path)?;
    let mut writer = BufWriter::new(file);

    // 80-byte header (can be anything, usually ignored)
    let header = b"Binary STL generated by RustMesh";
    let mut header_buf = [0u8; 80];
    let header_len = header.len().min(80);
    header_buf[..header_len].copy_from_slice(&header[..header_len]);
    writer.write_all(&header_buf)?;

    // Write triangle count (4 bytes, little-endian)
    let n_faces = mesh.n_faces() as u32;
    writer.write_all(&n_faces.to_le_bytes())?;

    // Write each triangle
    for fh in mesh.faces() {
        let verts: Vec<_> = mesh.face_vertices_vec(fh);
        if verts.len() < 3 {
            continue;
        }

        // For non-triangular faces, triangulate (fan triangulation)
        if verts.len() == 3 {
            write_triangle_binary(&mut writer, mesh, &verts)?;
        } else {
            // Fan triangulation for polygons
            let p0 = verts[0];
            for i in 1..verts.len() - 1 {
                let triangle = [p0, verts[i], verts[i + 1]];
                write_triangle_binary(&mut writer, mesh, &triangle)?;
            }
        }
    }

    writer.flush()?;
    Ok(())
}

/// Write a single triangle to binary STL
fn write_triangle_binary<W: Write>(
    writer: &mut W,
    mesh: &RustMesh,
    verts: &[crate::VertexHandle],
) -> io::Result<()> {
    let p0 = mesh.point(verts[0]).unwrap_or(glam::Vec3::ZERO);
    let p1 = mesh.point(verts[1]).unwrap_or(glam::Vec3::ZERO);
    let p2 = mesh.point(verts[2]).unwrap_or(glam::Vec3::ZERO);

    // Compute normal
    let edge1 = p1 - p0;
    let edge2 = p2 - p0;
    let normal = edge1.cross(edge2).normalize_or_zero();

    // Write normal (3 floats, 12 bytes)
    writer.write_all(&normal.x.to_le_bytes())?;
    writer.write_all(&normal.y.to_le_bytes())?;
    writer.write_all(&normal.z.to_le_bytes())?;

    // Write vertices (3 floats each, 36 bytes total)
    for p in [p0, p1, p2] {
        writer.write_all(&p.x.to_le_bytes())?;
        writer.write_all(&p.y.to_le_bytes())?;
        writer.write_all(&p.z.to_le_bytes())?;
    }

    // Attribute byte count (2 bytes, usually 0)
    writer.write_all(&[0u8, 0])?;

    Ok(())
}

// ============================================================================
// STL Reading Implementation
// ============================================================================

/// Read mesh from STL file
pub fn read_stl(path: impl AsRef<Path>) -> io::Result<RustMesh> {
    let path = path.as_ref();

    // Get file size to help determine format
    let metadata = std::fs::metadata(path)?;
    let file_size = metadata.len();

    // Read first 84 bytes (header + triangle count) to check format
    let file = File::open(path)?;
    let mut reader = BufReader::new(file);
    let mut header_plus_count = [0u8; 84];
    reader.read_exact(&mut header_plus_count)?;

    // Check if it could be ASCII (starts with "solid")
    let header_str = String::from_utf8_lossy(&header_plus_count[..80]);
    let starts_with_solid = header_str.trim().starts_with("solid");

    // For binary STL: file_size = 80 + 4 + n_triangles * 50
    // Check if file size matches binary format
    let n_triangles_bytes = &header_plus_count[80..84];
    let n_triangles = u32::from_le_bytes([
        n_triangles_bytes[0],
        n_triangles_bytes[1],
        n_triangles_bytes[2],
        n_triangles_bytes[3],
    ]);
    let expected_binary_size = 84 + (n_triangles as u64) * 50;
    let is_binary_size = file_size == expected_binary_size;

    // Determine format: binary if size matches, or ASCII if starts with solid and doesn't match binary
    let is_ascii = starts_with_solid && !is_binary_size;

    if is_ascii {
        // ASCII format - reread from beginning
        let file = File::open(path)?;
        let reader = BufReader::new(file);
        read_stl_ascii(reader)
    } else {
        // Binary format - we've already read header and count, now read triangles
        read_stl_binary_with_count(reader, n_triangles)
    }
}

/// Read ASCII STL file
fn read_stl_ascii(mut reader: BufReader<File>) -> io::Result<RustMesh> {
    let mut mesh = RustMesh::new();

    // Vertex deduplication: map positions to handles (use tuple key for hash)
    let mut vertex_map: HashMap<(i64, i64, i64), crate::VertexHandle> = HashMap::new();

    let mut line = String::new();

    loop {
        line.clear();
        if reader.read_line(&mut line)? == 0 {
            break;
        }

        let trimmed = line.trim();
        let parts: Vec<&str> = trimmed.split_whitespace().collect();

        if parts.is_empty() {
            continue;
        }

        match parts[0].to_lowercase().as_str() {
            "solid" => {
                // Skip solid line (name follows)
            }
            "endsolid" => {
                // End of file
                break;
            }
            "facet" => {
                // "facet normal nx ny nz" - normal is ignored for now
            }
            "outer" => {
                // "outer loop" - start of vertices
            }
            "vertex" => {
                // Collect 3 vertices
                let mut triangle_verts = Vec::with_capacity(3);
                triangle_verts.push(parse_vertex_line(&parts, &mut vertex_map, &mut mesh));

                // Read next two vertices
                for _ in 0..2 {
                    line.clear();
                    reader.read_line(&mut line)?;
                    let v_parts: Vec<&str> = line.trim().split_whitespace().collect();
                    triangle_verts.push(parse_vertex_line(&v_parts, &mut vertex_map, &mut mesh));
                }

                // Create face
                if triangle_verts.len() == 3 {
                    mesh.add_face(&triangle_verts);
                }
            }
            "endloop" | "endfacet" => {
                // These are just markers
            }
            _ => {}
        }
    }

    Ok(mesh)
}

/// Read binary STL file with triangle count already read
fn read_stl_binary_with_count(
    mut reader: BufReader<File>,
    n_triangles: u32,
) -> io::Result<RustMesh> {
    let mut mesh = RustMesh::new();

    // Vertex deduplication
    let mut vertex_map: HashMap<(i64, i64, i64), crate::VertexHandle> = HashMap::new();

    for _ in 0..n_triangles {
        // Read normal (12 bytes) - ignored for now
        let mut normal_bytes = [0u8; 12];
        reader.read_exact(&mut normal_bytes)?;

        // Read 3 vertices (36 bytes)
        let mut verts = Vec::with_capacity(3);
        for _ in 0..3 {
            let mut vert_bytes = [0u8; 12];
            reader.read_exact(&mut vert_bytes)?;

            let x =
                f32::from_le_bytes([vert_bytes[0], vert_bytes[1], vert_bytes[2], vert_bytes[3]]);
            let y =
                f32::from_le_bytes([vert_bytes[4], vert_bytes[5], vert_bytes[6], vert_bytes[7]]);
            let z =
                f32::from_le_bytes([vert_bytes[8], vert_bytes[9], vert_bytes[10], vert_bytes[11]]);

            let key = float_key(x, y, z);
            let vh = *vertex_map
                .entry(key)
                .or_insert_with(|| mesh.add_vertex(glam::Vec3::new(x, y, z)));
            verts.push(vh);
        }

        // Read attribute byte count (2 bytes, usually ignored)
        let mut attr_bytes = [0u8; 2];
        reader.read_exact(&mut attr_bytes)?;

        // Create face
        if verts.len() == 3 {
            mesh.add_face(&verts);
        }
    }

    Ok(mesh)
}

/// Convert float to hashable key (quantize to avoid float comparison issues)
fn float_key(x: f32, y: f32, z: f32) -> (i64, i64, i64) {
    // Quantize to 1e-6 precision for hashing
    // Use i64 to correctly handle negative values
    (
        (x * 1e6).round() as i64,
        (y * 1e6).round() as i64,
        (z * 1e6).round() as i64,
    )
}

/// Parse a vertex line and return or create a vertex handle
fn parse_vertex_line(
    parts: &[&str],
    vertex_map: &mut HashMap<(i64, i64, i64), crate::VertexHandle>,
    mesh: &mut RustMesh,
) -> crate::VertexHandle {
    if parts.len() >= 4 {
        let x = parts[1].parse().unwrap_or(0.0);
        let y = parts[2].parse().unwrap_or(0.0);
        let z = parts[3].parse().unwrap_or(0.0);
        let key = float_key(x, y, z);

        *vertex_map
            .entry(key)
            .or_insert_with(|| mesh.add_vertex(glam::Vec3::new(x, y, z)))
    } else {
        crate::VertexHandle::invalid()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn create_test_mesh() -> RustMesh {
        let mut mesh = RustMesh::new();
        let v0 = mesh.add_vertex(glam::Vec3::new(0.0, 0.0, 0.0));
        let v1 = mesh.add_vertex(glam::Vec3::new(1.0, 0.0, 0.0));
        let v2 = mesh.add_vertex(glam::Vec3::new(0.0, 1.0, 0.0));
        mesh.add_face(&[v0, v1, v2]);
        mesh
    }

    #[test]
    fn test_stl_ascii_write() {
        use std::fs;

        let mesh = create_test_mesh();
        let path = "/tmp/test_mesh.stl";
        write_stl(&mesh, path, StlFormat::Ascii).unwrap();

        assert!(std::path::Path::new(path).exists());

        // Check file content
        let content = fs::read_to_string(path).unwrap();
        assert!(content.starts_with("solid"));
        assert!(content.contains("facet normal"));
        assert!(content.contains("vertex"));

        fs::remove_file(path).ok();
    }

    #[test]
    fn test_stl_binary_write() {
        use std::fs;

        let mesh = create_test_mesh();
        let path = "/tmp/test_mesh_binary.stl";
        write_stl(&mesh, path, StlFormat::Binary).unwrap();

        assert!(std::path::Path::new(path).exists());

        // Check file size: 80 header + 4 count + 50 per triangle
        let metadata = fs::metadata(path).unwrap();
        let expected_size = 80 + 4 + 50; // 1 triangle
        assert_eq!(metadata.len() as usize, expected_size);

        fs::remove_file(path).ok();
    }

    #[test]
    fn test_stl_ascii_roundtrip() {
        use std::fs;

        let original = create_test_mesh();
        let path = "/tmp/test_stl_roundtrip.stl";

        // Write
        write_stl(&original, path, StlFormat::Ascii).unwrap();

        // Read
        let loaded = read_stl(path).unwrap();

        // Verify face count (vertex count may differ due to deduplication)
        assert_eq!(loaded.n_faces(), original.n_faces());

        fs::remove_file(path).ok();
    }

    #[test]
    fn test_stl_binary_roundtrip() {
        use std::fs;

        let original = create_test_mesh();
        let path = "/tmp/test_stl_binary_roundtrip.stl";

        // Write
        write_stl(&original, path, StlFormat::Binary).unwrap();

        // Read
        let loaded = read_stl(path).unwrap();

        // Verify face count
        assert_eq!(loaded.n_faces(), original.n_faces());

        fs::remove_file(path).ok();
    }

    #[test]
    fn test_stl_multi_triangle() {
        use std::fs;

        let mut mesh = RustMesh::new();
        // Create two triangles sharing an edge
        let v0 = mesh.add_vertex(glam::Vec3::new(0.0, 0.0, 0.0));
        let v1 = mesh.add_vertex(glam::Vec3::new(1.0, 0.0, 0.0));
        let v2 = mesh.add_vertex(glam::Vec3::new(0.0, 1.0, 0.0));
        let v3 = mesh.add_vertex(glam::Vec3::new(1.0, 1.0, 0.0));

        mesh.add_face(&[v0, v1, v2]);
        mesh.add_face(&[v1, v3, v2]);

        let path = "/tmp/test_stl_multi.stl";

        // Write and read
        write_stl(&mesh, path, StlFormat::Binary).unwrap();
        let loaded = read_stl(path).unwrap();

        assert_eq!(loaded.n_faces(), 2);

        fs::remove_file(path).ok();
    }
}
